version: '3'
services: 
    server:
        build: server/
        ports: 
            - "8080:80"
        networks: 
            - net1

    sandbox:
        build: sandbox/
        ports: 
            - "6040:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - net1
    client:
        build: client/
        networks:
            - net1 
networks:
    net1:
        external:
            name: net1